version: "2"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: arm.Dockerfile
    # logging:
    #   driver: "none"
    volumes:
      - ./nginx/app:/usr/share/nginx/html:ro
    ports:
      - "80:80"
      - "443:443"
    links:
      - expose-hardware
      - get-data
      - expose-db

  expose-hardware:
    build:
      context: ./expose-hardware
      dockerfile: arm.Dockerfile
    volumes:
      - ./expose-hardware:/usr/src/app:rw
      - /lib/modules:/lib/modules:rw
    # devices:
      # - /dev/mem
    cap_add:
      - SYS_RAWIO
    privileged: true

  get-data:
    build:
      context: ./get-data
      dockerfile: arm.Dockerfile
    volumes:
      - ./get-data:/usr/src/app:rw
      - /lib/modules:/lib/modules:rw
    # devices:
      # - /dev/mem
    cap_add:
      - SYS_RAWIO
    privileged: true

  expose-db:
    build: 
      context: ./expose-db
      dockerfile: arm.Dockerfile
    volumes:
      - ./expose-db:/usr/src/app:rw
    ports:
      - "5858:5858"
    links:
      - db

  db:
    image: hypriot/rpi-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=cosmicRoot
      - MYSQL_DATABASE=cosmic
      - MYSQL_USER=cosmic
      - MYSQL_PASSWORD=cosmicUser
    volumes:
      - ../db:/var/lib/mysql:rw
    ports: 
      - "3306:3306"
